apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpserver
  namespace: istio-system
spec:
  dnsNames:
  - httpserver.test.io
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: letsencrypt-dns
  secretName: httpserver
